/* generated by 'bin/codeGen/templateGenerate.js' */

// random number between min and max
export function random(min: number = 0, max: number = 1) {
    return min === 0 && max === 1
        ? Math.random()
        : (Math.random() * (max - min)) + min;
}

// random integer between min and max
export function randomInt(min: number = 0, max: number = 1) {
    return Math.floor(random(min, max));
}

// random fixed number between min and max
export function randomFixed(reserveDigits: number, min: number = 0, max: number = 1) {
    return Number(random(min, max).toFixed(reserveDigits));
}

// random hex color
export function randomHexColor() {
    return '#' + Math.floor(Math.random() * 0xffffff).toString(16);
}
