/* generated by 'bin/templateGenerate.js' */
type Contex = null | object;
type Argvs = any[];
type Throttle = (fn: Function,  wait?: number, ctx?: Contex) => (...argvs: Argvs) => void;

export const throttle: Throttle = (fn, wait = 300, ctx = null) => {
    let startTime = Date.now();

    return function(...argvs) {
        const runTime = Date.now();
        const isExpire = runTime - startTime > wait;

        if (isExpire) {
            startTime = runTime;
            fn.apply(ctx, argvs);
        }
    }
}
