/* generated by 'bin/codeGen/templateGenerate.js' */
import {rgba2Hex, hex2Rgba} from './index';

describe('color change is ok', () => {
    const rgba = 'rgba(0,154,97,1)';
    const hex = '#009A61FF';

    it('should return rgba(0,154,97,1)', () => {
        expect(hex2Rgba(hex)).toBe(rgba);
    });

    it('should return #009A61FF', () => {
        expect(rgba2Hex(rgba)).toBe(hex);
    });
});