/* generated by 'bin/codeGen/templateGenerate.js' */
import {rgbaToHex, hexToRgba} from './index';

describe('color change is ok', () => {
    const rgba = 'rgba(0,154,97,1)';
    const hex = '#009A61FF';

    it('should return rgba(0,154,97,1)', () => {
        expect(hexToRgba(hex)).toBe(rgba);
    });

    it('should return #009A61FF', () => {
        expect(rgbaToHex(rgba)).toBe(hex);
    });
});