/* generated by 'bin/templateGenerate.js' */

export function chunk(target: any[], count: number): any[] | typeof target {
    if (!Array.isArray(target)) {
        return target;
    }

    const result: any[] = [];
    for (let i = 0; i < target.length; i += count) {
        result.push(target.slice(i, i + count))
    }
    return result;
}
