/* generated by 'bin/methodTemplateGenerate.js' */

export function pipe(...funcs: Function[]): Function {
    return function (...args: any[]) {
        return funcs.reduce((initArgs, fun) => {
            return [fun(...initArgs)];
        }, args)[0]
    }
}
