/* generated by 'bin/templateGenerate.js' */

export function isJson(target: any) {
    try {
        const result = JSON.parse(target);
        return result;
    } catch (error) {
        return false;
    }
}
