/* generated by 'bin/codeGen/templateGenerate.js' */
import {setStyle} from '../utils';

type TCopy = (text: string) => Promise<any>;

const clipboard = window?.navigator?.clipboard;

const copyFn: TCopy = clipboard ? function(text) {
    return new Promise(function(resolve, reject) {
        clipboard.writeText(text)
            .then(() => {
                resolve(text);
            })
            .catch(error => {
                reject(error);
            })
    })
} : function(text) {
    return new Promise((resolve, reject) => {
        try {
            const input = document.createElement('input');
            input.value = text;
            setStyle(input, {
                position: 'fixed',
                left: '-9999px'
            });
            document.body.appendChild(input);
            input.select();
            document.execCommand('copy');
            document.body.removeChild(input);
            resolve(text);
        } catch (error) {
            reject(error);
        }
    });
}

export function copy(text: string) {
    return copyFn(text);
}
