/* generated by 'bin/codeGen/templateGenerate.js' */
import {customConvert, convertSize} from './index';

describe('convert methods are ok', () => {
    const contomUnits = ['mm', 'cm', 'm'];

    it('should return 1024', () => {
        expect(convertSize(1, 'mb', 'kB')).toBe(1024);
    });

    it('should return 0.5', () => {
        const convertLimit = customConvert(10, contomUnits);
        expect(convertLimit(5, 'MM', 'cm')).toBe(0.5);
    });
});