/* generated by 'bin/codeGen/templateGenerate.js' */
import {hasOwnProperty} from '../utils';

export function cache(fn: Function): (...argvs: any[]) => any {
    const cacheMap = Object.create(null);
    return function(...argvs) {
        const key  = JSON.stringify(argvs);
        if (hasOwnProperty(cacheMap, key)) {
            return cacheMap[key];
        }
        const result = fn.apply(null, argvs);
        return cacheMap[key] = result;
    };
}
